// Test-only, synthetic contract fixtures. Expected values are literal oracles,
// not snapshots generated by the production functions being tested.
// These are NOT accountant-certified tax-amount golden cases.
export const fixtureVersion = "2026-09-29.1";
export const professionalReview = "PENDING";
export const sourceCheckedAt = "2026-09-29";

export interface PeriodCase {
  id: string;
  description: string;
  now: string;
  expected: {
    today: string;
    current: string;
    period: string;
    due: string;
    days: number;
  };
}

// Ordinary monthly IVA/ISR base deadline only. No RFC extensions, DIOT,
// exceptional decrees, or bank-specific Friday payment extensions assumed.
export const periodCases: readonly PeriodCase[] = [
  { id: "PER-001", description: "Previous completed month", now: "2026-09-07T18:00:00Z",
    expected: { today: "2026-09-07", current: "2026-09", period: "2026-08", due: "2026-09-17", days: 10 } },
  { id: "PER-002", description: "UTC September is still August in Mexico", now: "2026-09-01T05:59:59.999Z",
    expected: { today: "2026-08-31", current: "2026-08", period: "2026-07", due: "2026-08-17", days: -14 } },
  { id: "PER-003", description: "Mexico midnight changes the operating month", now: "2026-09-01T06:00:00Z",
    expected: { today: "2026-09-01", current: "2026-09", period: "2026-08", due: "2026-09-17", days: 16 } },
  { id: "PER-004", description: "UTC January is still the previous year in Mexico", now: "2026-01-01T05:59:59.999Z",
    expected: { today: "2025-12-31", current: "2025-12", period: "2025-11", due: "2025-12-17", days: -14 } },
  { id: "PER-005", description: "January rollover and Saturday deadline", now: "2026-01-01T06:00:00Z",
    expected: { today: "2026-01-01", current: "2026-01", period: "2025-12", due: "2026-01-19", days: 18 } },
  { id: "PER-006", description: "Due today is not overdue before Mexico midnight", now: "2026-09-18T05:59:59.999Z",
    expected: { today: "2026-09-17", current: "2026-09", period: "2026-08", due: "2026-09-17", days: 0 } },
  { id: "PER-007", description: "Overdue starts at Mexico midnight", now: "2026-09-18T06:00:00Z",
    expected: { today: "2026-09-18", current: "2026-09", period: "2026-08", due: "2026-09-17", days: -1 } },
  { id: "PER-008", description: "Third Monday of November moves the deadline", now: "2025-11-03T18:00:00Z",
    expected: { today: "2025-11-03", current: "2025-11", period: "2025-10", due: "2025-11-18", days: 15 } },
  { id: "PER-009", description: "September filing deadline falls on Saturday", now: "2026-10-01T06:00:00Z",
    expected: { today: "2026-10-01", current: "2026-10", period: "2026-09", due: "2026-10-19", days: 18 } },
  { id: "PER-010", description: "Leap February followed by Sunday and March holiday", now: "2024-03-01T06:00:00Z",
    expected: { today: "2024-03-01", current: "2024-03", period: "2024-02", due: "2024-03-19", days: 18 } },
];

export interface CloseCase {
  id: string;
  description: string;
  input: {
    now: string;
    period: string;
    onboarded: string;
    bankTotal: number;
    bankPending: number;
    noBankConfirmed: boolean;
    accounting: "DRAFT" | "POSTED" | "CLOSED";
    declaration: "CALCULATED" | "FILED" | "PAID" | null;
    historical: boolean;
    enginesAvailable: boolean;
  };
  expected: {
    coverage: "NO_DATA" | "NO_ACTIVITY_CONFIRMED" | "PENDING" | "RECONCILED";
    percentage: number | null;
    checklistBank: "listo" | "pendiente" | "atencion" | null;
    readinessBank: "ok" | "error" | null;
    closeBank: "listo" | "bloquea" | "sin_datos";
    phase: "BLOQUEADO" | "LISTO" | "CONTABILIZADO" | "CERRADO";
    declared: boolean;
    paid: boolean;
    downloadable: boolean;
    origin: "CONTABILIDAD_OS" | "FUERA_DE_CONTABILIDAD_OS" | null;
    compliance: "FILED" | "OVERDUE" | "NOT_APPLICABLE";
  };
}

const closeInput: CloseCase["input"] = {
  now: "2026-09-29T18:00:00Z", period: "2026-07", onboarded: "2026-01-01T12:00:00Z",
  bankTotal: 0, bankPending: 0, noBankConfirmed: false,
  accounting: "DRAFT", declaration: "CALCULATED", historical: false, enginesAvailable: true,
};
const septemberOnboarding = "2026-09-01T12:00:00Z";

export const closeCases: readonly CloseCase[] = [
  { id: "CLOSE-001", description: "Zero of zero is missing evidence, not reconciliation",
    input: { ...closeInput },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: "atencion", readinessBank: "error", closeBank: "bloquea", phase: "BLOQUEADO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-002", description: "Explicit no-bank confirmation opens the gate without inventing a percentage",
    input: { ...closeInput, noBankConfirmed: true },
    expected: { coverage: "NO_ACTIVITY_CONFIRMED", percentage: null, checklistBank: "listo", readinessBank: "ok", closeBank: "listo", phase: "LISTO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-003", description: "Reconciled evidence is ready but not yet in the ledger",
    input: { ...closeInput, bankTotal: 10 },
    expected: { coverage: "RECONCILED", percentage: 100, checklistBank: "listo", readinessBank: "ok", closeBank: "listo", phase: "LISTO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-004", description: "Partially reconciled bank data blocks the close",
    input: { ...closeInput, bankTotal: 10, bankPending: 2 },
    expected: { coverage: "PENDING", percentage: 80, checklistBank: "pendiente", readinessBank: "ok", closeBank: "bloquea", phase: "BLOQUEADO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-005", description: "Filed plus a clean local ledger is closed, not necessarily paid",
    input: { ...closeInput, bankTotal: 10, accounting: "POSTED", declaration: "FILED" },
    expected: { coverage: "RECONCILED", percentage: 100, checklistBank: "listo", readinessBank: "ok", closeBank: "listo", phase: "CERRADO", declared: true, paid: false, downloadable: true, origin: "CONTABILIDAD_OS", compliance: "FILED" } },
  { id: "CLOSE-006", description: "A local ledger and saved draft do not imply filing",
    input: { ...closeInput, bankTotal: 10, accounting: "POSTED" },
    expected: { coverage: "RECONCILED", percentage: 100, checklistBank: "listo", readinessBank: "ok", closeBank: "listo", phase: "CONTABILIZADO", declared: false, paid: false, downloadable: true, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-007", description: "A late evidence gap overrides a local CLOSED flag without erasing filing",
    input: { ...closeInput, accounting: "CLOSED", declaration: "FILED" },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: "atencion", readinessBank: "error", closeBank: "bloquea", phase: "BLOQUEADO", declared: true, paid: false, downloadable: false, origin: null, compliance: "FILED" } },
  { id: "CLOSE-008", description: "September onboarding imports a July filed external close without local entries",
    input: { ...closeInput, onboarded: septemberOnboarding, declaration: "FILED", historical: true },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: "atencion", readinessBank: "error", closeBank: "bloquea", phase: "CERRADO", declared: true, paid: false, downloadable: false, origin: "FUERA_DE_CONTABILIDAD_OS", compliance: "FILED" } },
  { id: "CLOSE-009", description: "An imported paid declaration is both filed and paid, but has no local ledger",
    input: { ...closeInput, onboarded: septemberOnboarding, declaration: "PAID", historical: true },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: "atencion", readinessBank: "error", closeBank: "bloquea", phase: "CERRADO", declared: true, paid: true, downloadable: false, origin: "FUERA_DE_CONTABILIDAD_OS", compliance: "FILED" } },
  { id: "CLOSE-010", description: "A historical draft is not a filed external close and remains overdue",
    input: { ...closeInput, onboarded: septemberOnboarding, historical: true },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: "atencion", readinessBank: "error", closeBank: "bloquea", phase: "BLOQUEADO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-011", description: "A pre-onboarding period without a declaration is not fabricated as filed",
    input: { ...closeInput, onboarded: septemberOnboarding, declaration: null },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: "atencion", readinessBank: "error", closeBank: "bloquea", phase: "BLOQUEADO", declared: false, paid: false, downloadable: false, origin: null, compliance: "NOT_APPLICABLE" } },
  { id: "CLOSE-012", description: "External filing survives unavailable engines; unknown amounts stay unknown",
    input: { ...closeInput, onboarded: septemberOnboarding, declaration: "FILED", historical: true, enginesAvailable: false },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: null, readinessBank: null, closeBank: "sin_datos", phase: "CERRADO", declared: true, paid: false, downloadable: false, origin: "FUERA_DE_CONTABILIDAD_OS", compliance: "FILED" } },
  { id: "CLOSE-013", description: "Unavailable engines cannot make an ordinary period ready",
    input: { ...closeInput, declaration: null, enginesAvailable: false },
    expected: { coverage: "NO_DATA", percentage: null, checklistBank: null, readinessBank: null, closeBank: "sin_datos", phase: "BLOQUEADO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
  { id: "CLOSE-014", description: "A no-bank confirmation cannot hide newly arrived unreconciled transactions",
    input: { ...closeInput, bankTotal: 10, bankPending: 2, noBankConfirmed: true },
    expected: { coverage: "PENDING", percentage: 80, checklistBank: "pendiente", readinessBank: "ok", closeBank: "bloquea", phase: "BLOQUEADO", declared: false, paid: false, downloadable: false, origin: null, compliance: "OVERDUE" } },
];

export interface RegimeCase {
  id: string;
  description: string;
  calculation: "MONTHLY" | "ANNUAL";
  rfc: string;
  scalar: string;
  period: string;
  rows: readonly { code: string; since: string | null; endedAt: string | null; active: boolean }[];
  expected: {
    codes: readonly string[];
    track: string | null;
    reason: "ASSISTED_ONLY" | "ENGINE_NOT_IMPLEMENTED" | "NOT_APPLICABLE" | "UNKNOWN_REGIME" | "INCOMPATIBLE_TAXPAYER_TYPE" | "MULTI_REGIME_COMPOSITION_REQUIRED" | null;
  };
}

// Synthetic RFCs encode only the PF/PM shape; they identify no customer.
const pf = "AAAA010101AAA";
const pm = "AAA010101AAA";
const regimeInput = { calculation: "MONTHLY" as const, rfc: pf, period: "2026-08", rows: [] };
const mixedRows = [
  { code: "612", since: null, endedAt: null, active: true },
  { code: "606", since: null, endedAt: null, active: true },
];
const companionRows = [mixedRows[0], { code: "605", since: null, endedAt: null, active: true }];
const historicalRows = [
  { code: "608", since: "2024-01-01T00:00:00Z", endedAt: "2026-01-01T00:00:00Z", active: false },
  { code: "612", since: "2026-01-01T00:00:00Z", endedAt: null, active: true },
];

export const regimeCases: readonly RegimeCase[] = [
  { ...regimeInput, id: "REG-001", description: "General PM monthly engine enabled", rfc: pm, scalar: "601",
    expected: { codes: ["601"], track: "601", reason: null } },
  { ...regimeInput, id: "REG-002", description: "PFAE monthly engine enabled", scalar: "612",
    expected: { codes: ["612"], track: "612", reason: null } },
  { ...regimeInput, id: "REG-003", description: "Rentals monthly engine enabled", scalar: "606",
    expected: { codes: ["606"], track: "606", reason: null } },
  { ...regimeInput, id: "REG-004", description: "Platforms monthly engine enabled", scalar: "625",
    expected: { codes: ["625"], track: "625", reason: null } },
  { ...regimeInput, id: "REG-005", description: "RESICO PF monthly engine enabled", scalar: "626",
    expected: { codes: ["626"], track: "626-PF", reason: null } },
  { ...regimeInput, id: "REG-006", description: "General PM annual engine enabled", calculation: "ANNUAL", rfc: pm, scalar: "601",
    expected: { codes: ["601"], track: "601", reason: null } },
  { ...regimeInput, id: "REG-007", description: "PFAE annual engine enabled", calculation: "ANNUAL", scalar: "612",
    expected: { codes: ["612"], track: "612", reason: null } },
  { ...regimeInput, id: "REG-008", description: "RESICO PM cannot fall through to RESICO PF", rfc: pm, scalar: "626",
    expected: { codes: ["626"], track: "626-PM", reason: "ENGINE_NOT_IMPLEMENTED" } },
  { ...regimeInput, id: "REG-009", description: "Nonprofit PM remains assisted", rfc: pm, scalar: "603",
    expected: { codes: ["603"], track: "603", reason: "ASSISTED_ONLY" } },
  { ...regimeInput, id: "REG-010", description: "No fiscal obligations is not a calculated zero", scalar: "616",
    expected: { codes: ["616"], track: "616", reason: "NOT_APPLICABLE" } },
  { ...regimeInput, id: "REG-011", description: "Unknown regime fails closed", scalar: "999",
    expected: { codes: ["999"], track: null, reason: "UNKNOWN_REGIME" } },
  { ...regimeInput, id: "REG-012", description: "Two monthly engines require explicit composition", scalar: "612", rows: mixedRows,
    expected: { codes: ["612", "606"], track: "612", reason: "MULTI_REGIME_COMPOSITION_REQUIRED" } },
  { ...regimeInput, id: "REG-013", description: "Salary companion does not contaminate the monthly PFAE engine", scalar: "612", rows: companionRows,
    expected: { codes: ["612", "605"], track: "612", reason: null } },
  { ...regimeInput, id: "REG-014", description: "Salary companion still requires annual composition", calculation: "ANNUAL", scalar: "612", rows: companionRows,
    expected: { codes: ["612", "605"], track: "612", reason: "MULTI_REGIME_COMPOSITION_REQUIRED" } },
  { ...regimeInput, id: "REG-015", description: "Historical period uses the old regime, not today's scalar", scalar: "612", period: "2025-08", rows: historicalRows,
    expected: { codes: ["608"], track: "608", reason: "ASSISTED_ONLY" } },
  { ...regimeInput, id: "REG-016", description: "Ended regime is excluded at the half-open boundary", scalar: "612", period: "2026-01", rows: historicalRows,
    expected: { codes: ["612"], track: "612", reason: null } },
  { ...regimeInput, id: "REG-017", description: "PM-only regime cannot calculate for a PF", scalar: "601",
    expected: { codes: ["601"], track: "601", reason: "INCOMPATIBLE_TAXPAYER_TYPE" } },
  { ...regimeInput, id: "REG-018", description: "Annual historical calculation cannot use today's supported regime", calculation: "ANNUAL", scalar: "612", period: "2025-08", rows: historicalRows,
    expected: { codes: ["608"], track: "608", reason: "ASSISTED_ONLY" } },
];
