"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { ReviewOperation, ReviewRequest } from "@/lib/bancos/statements/review";
import { BankDocumentUpload } from "./BankDocumentUpload";
import { usePeriod } from "@/components/contabilidad/PeriodProvider";
type Pendiente = { batchId: string; bankAccountId: string; periodo: string | null; year: number | null; month: number | null; listo: boolean; motivos: string[]; archivoNombre: string | null; cuenta: string };
// La cuenta elegida desde «Estados por revisar» sobrevive al remontaje que
// provoca cambiar de periodo (la página monta este componente por mes).
let cuentaPreferida = "";
type Movement = { id: string; date: string; amount: number; description: string; reference?: string; time?: string; tracking?: string; bankId?: string; source?: string };
type SourceRow = { id: string; rowNumber: number; pageNumber: number | null; parsed: Movement; movementId: string | null; status: string; candidateIds: string[] };
type Item = { type: "row"; id: string; filename: string; row: number; page: number | null; evidence: Movement; reason: string; candidates: Movement[] } | { type: "pair"; key: string; ids: string[]; reason: string; movements: Movement[] };
type Document = { id: string; archivoNombre: string; source: string; originalUrl: string | null; sourceRows: number; linked: number; unresolved: number; saldoInicial: number | string | null; saldoFinal: number | string | null; controls: { credits?: number; debits?: number; creditCount?: number; debitCount?: number } | null; warnings: unknown; periodStart: string | null; periodEnd: string | null };
type Review = { hash: string; status: string; canWrite: boolean; closed: boolean; movementCount: number; unresolvedCount: number; duplicateCaseCount: number; documents: Document[]; items: Item[]; totalItems: number; nextCursor: number | null; verifiedDocumentId: string | null };
const inputClass = "rounded border border-cos-line bg-cos-canvas p-2 text-sm";
const buttonClass = "rounded border border-cos-line px-3 py-1.5 text-sm hover:bg-cos-paper disabled:opacity-40";
const money = (n: number) => n.toLocaleString("es-MX", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
function MovementLine({ movement }: { movement: Movement }) { return <div className="rounded bg-cos-canvas p-2 text-sm"><span className="font-medium">{movement.date} · ${money(movement.amount)}</span><p>{movement.description}</p><p className="text-xs text-cos-ink-faint">{[movement.source, movement.time, movement.reference, movement.tracking, movement.bankId].filter(Boolean).join(" · ")}<br />{movement.id}</p></div>; }
export function BankStatementReview({ companyId, year, month }: { companyId: string; year: number; month: number }) {
  const [accounts, setAccounts] = useState<{ id: string; nombre: string; banco: string }[]>([]), [accountId, setAccountId] = useState("");
  const [review, setReview] = useState<Review | null>(null), [cursor, setCursor] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [reason, setReason] = useState(""), [selected, setSelected] = useState<Record<string, string>>({});
  const [preview, setPreview] = useState<{ request: ReviewRequest; summary: string; ledgerEffect: { accountId: string; accountCode: string; accountName: string; original: string; reversal: string; amount: number }[] } | null>(null);
  const [rows, setRows] = useState<{ documentId: string; items: ((SourceRow & { type: "source_row" }) | (Movement & { type: "uncovered_movement" }))[]; nextCursor: number | null; uncoveredCount: number } | null>(null);
  const [pendientes, setPendientes] = useState<Pendiente[] | null>(null);
  const { setPeriod } = usePeriod();
  const dialog = useRef<HTMLDialogElement>(null), epoch = useRef(0);
  const period = `${year}-${String(month).padStart(2, "0")}`;
  const query = new URLSearchParams({ companyId, bankAccountId: accountId, year: String(year), month: String(month) }).toString();
  const refresh = useCallback(async () => {
    if (!accountId) return; const run = ++epoch.current; setBusy(true); setError("");
    try { const r = await fetch(`/api/bancos/statement-review?${query}&cursor=${cursor}`, { cache: "no-store" }); const data = await r.json(); if (!r.ok) throw new Error(data.error); if (run === epoch.current) setReview(data); }
    catch (e) { if (run === epoch.current) { setReview(null); setError(e instanceof Error ? e.message : "No se pudo cargar la revisión."); } }
    finally { if (run === epoch.current) setBusy(false); }
  }, [accountId, query, cursor]);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/bancos?companyId=${encodeURIComponent(companyId)}`, { signal: controller.signal }).then(async (r) => { const data = await r.json(); if (!r.ok || !Array.isArray(data)) throw new Error(data.error ?? "No se pudieron cargar las cuentas."); setAccounts(data); setAccountId(data.some((a: { id: string }) => a.id === cuentaPreferida) ? cuentaPreferida : data[0]?.id ?? ""); }).catch((e) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [companyId]);
  useEffect(() => { setReview(null); setRows(null); setPreview(null); setCursor(0); setReason(""); }, [companyId, accountId, year, month]);
  useEffect(() => { void refresh(); return () => { epoch.current++; }; }, [refresh]);
  const cargarPendientes = useCallback(async () => {
    try { const r = await fetch(`/api/bancos/statement-review?pendientes=1&companyId=${encodeURIComponent(companyId)}`, { cache: "no-store" }); const data = await r.json(); if (r.ok) setPendientes(data.items); }
    catch { /* la lista es ayuda; la revisión del mes sigue disponible */ }
  }, [companyId]);
  useEffect(() => { void cargarPendientes(); }, [cargarPendientes]);
  async function verificarSolo(batchId: string) {
    setBusy(true); setError(""); setMessage("");
    try { const r = await fetch("/api/bancos/statement-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "auto", companyId, batchId }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error);
      if (data.verificado) setMessage("Estado verificado automáticamente."); else setError("No se pudo verificar solo: " + (data.motivos?.join(" ") || "revisa el documento."));
    } catch (e) { setError(e instanceof Error ? e.message : "No se pudo verificar."); }
    finally { setBusy(false); await Promise.all([refresh(), cargarPendientes()]); }
  }
  function abrir(p: Pendiente) {
    cuentaPreferida = p.bankAccountId; setAccountId(p.bankAccountId);
    if (p.year && p.month && (p.year !== year || p.month !== month)) setPeriod(p.year, p.month);
  }
  useEffect(() => { if (preview) dialog.current?.showModal(); else dialog.current?.close(); }, [preview]);
  async function prepare(operation: ReviewOperation) {
    if (!review) return; setBusy(true); setError("");
    const request = { companyId, bankAccountId: accountId, year, month, expected: review.hash, operation };
    try { const r = await fetch("/api/bancos/statement-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "preview", request }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error);
      setPreview({ request: { ...request, effectExpected: data.effectExpected }, summary: data.summary, ledgerEffect: data.ledgerEffect });
    } catch (e) { setError(e instanceof Error ? e.message : "No se pudo preparar la decisión."); } finally { setBusy(false); }
  }
  async function confirm() {
    if (!preview) return; setBusy(true); setError("");
    try { const r = await fetch("/api/bancos/statement-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "confirm", request: preview.request }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error);
      setMessage(data.message); setPreview(null); setRows(null); setReason(""); await refresh();
    } catch (e) { setError(e instanceof Error ? e.message : "No se pudo confirmar."); } finally { setBusy(false); }
  }
  async function openRows(documentId: string, page = 0) {
    setBusy(true); setError("");
    try { const r = await fetch(`/api/bancos/statement-review?${query}&documentId=${encodeURIComponent(documentId)}&cursor=${page}`); const data = await r.json(); if (!r.ok) throw new Error(data.error); setRows(data); }
    catch (e) { setError(e instanceof Error ? e.message : "No se pudo leer el documento."); } finally { setBusy(false); }
  }
  const readOnly = busy || !review?.canWrite || review.closed;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center gap-2"><label className="text-sm">Cuenta <select aria-label="Cuenta a revisar" className={inputClass} disabled={busy} value={accountId} onChange={(e) => setAccountId(e.target.value)}>{!accounts.length && <option value="">Sin cuentas</option>}{accounts.map((a) => <option key={a.id} value={a.id}>{a.banco} · {a.nombre}</option>)}</select></label><button className={buttonClass} onClick={refresh} disabled={busy}>Actualizar</button>
      <BankDocumentUpload key={companyId} companyId={companyId} month={period} disabled={busy || (review ? !review.canWrite : false)} onUploaded={(d) => { setMessage(d.message); setAccountId(d.bankAccountId); void refresh(); }} /></div>
    {error && <p role="alert" className="rounded border border-red-300 p-3 text-sm text-red-600">{error}</p>}{message && <p role="status" className="text-sm text-cos-brand-ink">{message}</p>}
    {busy && <p role="status" className="text-sm text-cos-ink-soft">Consultando evidencia…</p>}
    {pendientes && pendientes.length > 0 && <section className="rounded-xl border border-amber-300 bg-cos-card p-4"><h2 className="font-semibold">Estados por revisar · {pendientes.length}</h2><p className="mt-1 text-sm text-cos-ink-soft">De todos los meses y cuentas. Los estados que cuadran contra sus totales impresos se verifican solos; aquí quedan sólo los que necesitan atención.</p>
      <ul className="mt-3 divide-y divide-cos-line">{pendientes.map((p) => <li key={p.batchId} className="flex flex-wrap items-center justify-between gap-2 py-2"><div className="min-w-0"><p className="text-sm font-medium">{p.periodo ?? "Sin mes"} · {p.cuenta}</p><p className="text-xs text-cos-ink-soft">{p.archivoNombre}{p.motivos[0] ? ` · ${p.motivos.join(" ")}` : ""}</p></div><div className="flex gap-2">{p.listo && <button className={buttonClass} disabled={busy || review?.canWrite === false} onClick={() => verificarSolo(p.batchId)}>Verificar</button>}<button className={buttonClass} disabled={busy} onClick={() => abrir(p)}>Abrir</button></div></li>)}</ul></section>}
    {review && <>
      <div className="rounded-xl border border-cos-line bg-cos-card p-4"><h2 className="font-semibold">{period} · {review.status === "VERIFIED" ? "Estado verificado" : review.status === "CHANGED" ? "La evidencia cambió" : "Información provisional"}</h2><p className="mt-1 text-sm text-cos-ink-soft">{review.movementCount} movimientos · {review.unresolvedCount} filas por revisar · {review.duplicateCaseCount} pares por confirmar</p><p className="mt-2 text-sm">La verificación exige el estado completo, saldos, cargos y abonos por separado. Puedes clasificar durante el mes; la contabilización espera la verificación.</p>{review.closed && <p className="mt-2 text-sm">Periodo cerrado: consulta disponible; correcciones bloqueadas.</p>}</div>
      <section className="space-y-3"><h2 className="font-semibold">Documentos y versiones</h2>{!review.documents.length && <p className="text-sm text-cos-ink-soft">Falta el original del mes. Adjunta el estado para comprobar la cobertura.</p>}{review.documents.map((doc) => <div key={doc.id} className="rounded-xl border border-cos-line bg-cos-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-medium">{doc.archivoNombre || doc.source}</h3><p className="text-xs text-cos-ink-soft">{doc.sourceRows} filas · {doc.linked} vinculadas · {doc.unresolved} pendientes</p></div><div className="flex gap-2">{doc.originalUrl && <a className={buttonClass} href={doc.originalUrl} target="_blank" rel="noreferrer">Ver original</a>}<button className={buttonClass} disabled={busy} onClick={() => openRows(doc.id)}>Ver filas y faltantes</button></div></div>
        {Array.isArray(doc.warnings) && doc.warnings.length > 0 && <p className="mt-2 text-xs text-amber-700">{doc.warnings.map(String).join(" · ")}</p>}
        {review.verifiedDocumentId === doc.id ? <button className={`${buttonClass} mt-3`} disabled={readOnly || reason.trim().length < 8} onClick={() => prepare({ type: "reopen", batchId: doc.id, reason })}>Reabrir verificación</button> : <details className="mt-3"><summary className="cursor-pointer text-sm text-cos-brand-ink">Verificar este estado completo</summary><VerificationForm key={`${doc.id}-${review.hash}`} document={doc} year={year} month={month} disabled={readOnly} onPreview={prepare} motivos={pendientes?.find((p) => p.batchId === doc.id)?.motivos ?? []} /></details>}
        {review.verifiedDocumentId !== doc.id && pendientes?.find((p) => p.batchId === doc.id)?.listo && <button className={`${buttonClass} mt-2`} disabled={readOnly} onClick={() => verificarSolo(doc.id)}>Verificar automáticamente</button>}
      </div>)}</section>
      <section className="space-y-3"><h2 className="font-semibold">Decisiones pendientes</h2><label className="block text-sm">Motivo y evidencia de la decisión<textarea aria-label="Motivo y evidencia" className={`${inputClass} mt-1 w-full`} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Por ejemplo: el banco confirma dos pagos con referencias distintas…" /></label>
        {review.items.map((item) => <div key={item.type === "row" ? item.id : item.key} className="space-y-2 rounded-xl border border-cos-line p-4"><p className="text-sm font-medium">{item.reason}</p>{item.type === "row" ? <><p className="text-xs text-cos-ink-soft">{item.filename} · fila {item.row}{item.page ? ` · página ${item.page}` : ""}</p><MovementLine movement={item.evidence} />{item.candidates.map((m) => <MovementLine key={m.id} movement={m} />)}{item.candidates.length > 0 && <select aria-label="Movimiento candidato" className={`${inputClass} w-full`} value={selected[item.id] ?? ""} onChange={(e) => setSelected({ ...selected, [item.id]: e.target.value })}><option value="">Selecciona el movimiento existente</option>{item.candidates.map((m) => <option key={m.id} value={m.id}>{m.date} · ${money(m.amount)} · {m.id}</option>)}</select>}<div className="flex flex-wrap gap-2">{([['LINK','Es la misma operación'],['NEW','Es otro pago real'],['EXCLUDE','Excluir fila'],['REPLACE','Corregir con esta versión']] as const).map(([resolution,label]) => <button key={resolution} className={buttonClass} disabled={readOnly || reason.trim().length < 8 || ((resolution === 'LINK' || resolution === 'REPLACE') && !selected[item.id])} onClick={() => prepare({ type: "row", rowId: item.id, resolution, ...(selected[item.id] ? { movementId: selected[item.id] } : {}), reason })}>{label}</button>)}</div></> : <>{item.movements.map((m) => <MovementLine key={m.id} movement={m} />)}<div className="flex flex-wrap gap-2"><button className={buttonClass} disabled={readOnly || reason.trim().length < 8} onClick={() => prepare({ type: "pair", primaryId: item.ids[0], secondaryId: item.ids[1], resolution: "KEEP_BOTH", reason })}>Son dos pagos: conservar ambos</button>{item.ids.map((id,index) => <button key={id} className={buttonClass} disabled={readOnly || reason.trim().length < 8} onClick={() => prepare({ type: "pair", primaryId: id, secondaryId: item.ids[1-index], resolution: "MERGE", reason })}>Conservar {index + 1}; revisar retirada de {2-index}</button>)}</div></>}</div>)}
        {!review.items.length && <p className="text-sm text-cos-ink-soft">No hay decisiones pendientes en esta página. Revisa también las filas y faltantes de cada documento.</p>}
        <div className="flex items-center gap-3"><button className={buttonClass} disabled={busy || cursor === 0} onClick={() => setCursor(Math.max(0, cursor-50))}>Anterior</button><span className="text-sm">{review.totalItems} casos</span><button className={buttonClass} disabled={busy || review.nextCursor === null} onClick={() => setCursor(review.nextCursor!)}>Siguiente</button></div>
      </section>
      {rows && <section className="space-y-2 rounded-xl border border-cos-line p-4"><h2 className="font-semibold">Filas del documento · {rows.uncoveredCount} movimientos sin cobertura</h2>{rows.items.map((row) => row.type === "source_row" ? <div key={row.id} className="space-y-2 border-b border-cos-line py-2"><p className="text-xs">Fila {row.rowNumber}{row.pageNumber ? ` · página ${row.pageNumber}` : ""} · {row.status}</p><MovementLine movement={row.parsed} /><button className={buttonClass} disabled={readOnly || row.status === "EXCLUDED" || reason.trim().length < 8} onClick={() => prepare({ type: "row", rowId: row.id, resolution: "EXCLUDE", reason })}>Revisar exclusión de esta fila</button></div> : <div key={row.id}><p className="text-xs text-amber-700">Sin cobertura en este documento</p><MovementLine movement={row} /></div>)}{rows.nextCursor !== null && <button className={buttonClass} disabled={busy} onClick={() => openRows(rows.documentId, rows.nextCursor!)}>Siguientes filas</button>}</section>}
    </>}
    <dialog ref={dialog} onCancel={(e) => { if (busy) e.preventDefault(); else setPreview(null); }} onClose={() => setPreview(null)} className="m-auto max-h-[85vh] w-[min(640px,94vw)] overflow-auto rounded-xl border border-cos-line bg-cos-card p-5 text-cos-ink shadow-xl backdrop:bg-black/40"><h2 className="font-semibold">Confirmar decisión bancaria</h2><p className="my-3 text-sm">{preview?.summary}</p>{preview?.ledgerEffect.map((e,i) => <p key={i} className="text-sm">Cuenta {e.accountCode} {e.accountName}: conservar {e.original} ${money(e.amount)} y crear {e.reversal} ${money(e.amount)}.</p>)}{error && <p role="alert" className="my-3 text-sm text-red-600">{error}</p>}<div className="mt-4 flex gap-2"><button className={buttonClass} disabled={busy} onClick={() => setPreview(null)}>Cancelar</button><button className="rounded bg-cos-brand px-4 py-2 text-sm text-white disabled:opacity-40" disabled={busy} onClick={confirm}>Confirmar decisión</button></div></dialog>
  </div>;
}
function VerificationForm({ document, year, month, disabled, onPreview, motivos }: { document: Document; year: number; month: number; disabled: boolean; onPreview: (operation: ReviewOperation) => void; motivos: string[] }) {
  const mesInicio = `${year}-${String(month).padStart(2, "0")}-01`, mesFin = new Date(Date.UTC(year, month, 0)).toISOString().slice(0, 10);
  const [values,setValues] = useState({ opening: document.saldoInicial == null ? "" : String(document.saldoInicial), closing: document.saldoFinal == null ? "" : String(document.saldoFinal), credits: document.controls?.credits == null ? "" : String(document.controls.credits), debits: document.controls?.debits == null ? "" : String(document.controls.debits), creditCount: document.controls?.creditCount == null ? "" : String(document.controls.creditCount), debitCount: document.controls?.debitCount == null ? "" : String(document.controls.debitCount) });
  const [checks,setChecks] = useState({ countsUnavailable: document.controls != null && (document.controls.creditCount == null || document.controls.debitCount == null), accountConfirmed: false, coverageConfirmed: false, originalReviewed: false }), [reason,setReason] = useState("Revisé el original y corregí lo que no cuadraba.");
  const [start,setStart] = useState(document.periodStart ?? mesInicio), [end,setEnd] = useState(document.periodEnd ?? mesFin);
  const leido = (key: string) => ({ opening: document.saldoInicial, closing: document.saldoFinal, credits: document.controls?.credits, debits: document.controls?.debits, creditCount: document.controls?.creditCount, debitCount: document.controls?.debitCount } as Record<string, unknown>)[key] != null;
  return <form className="mt-3 space-y-3" onSubmit={(e) => { e.preventDefault(); onPreview({ type: "verify", batchId: document.id, opening: Number(values.opening), closing: Number(values.closing), credits: Number(values.credits), debits: Number(values.debits), creditCount: values.creditCount === "" ? null : Number(values.creditCount), debitCount: values.debitCount === "" ? null : Number(values.debitCount), ...checks, periodStart: start, periodEnd: end, reason }); }}>
    {motivos.length > 0 && <div role="alert" className="rounded border border-amber-300 p-2 text-sm text-amber-800"><p className="font-medium">Por qué no se verificó solo:</p><ul className="list-disc pl-5">{motivos.map((m, i) => <li key={i}>{m}</li>)}</ul></div>}
    <p className="text-sm text-cos-ink-soft">Los valores marcados «leído del PDF» vienen del original del {year}-{String(month).padStart(2,"0")}. Compáralos y corrige sólo el que no coincida.</p><div className="grid gap-3 sm:grid-cols-2">{([['opening','Saldo inicial'],['closing','Saldo final'],['credits','Total de abonos'],['debits','Total de cargos'],['creditCount','Número de abonos'],['debitCount','Número de cargos']] as const).map(([key,label]) => <label key={key} className="text-sm">{label}{leido(key) && <span className="ml-1 text-xs text-cos-ink-faint">· leído del PDF</span>}<input aria-label={label} type="number" step={key.endsWith("Count") ? "1" : "0.01"} required={!key.endsWith("Count") || !checks.countsUnavailable} value={values[key]} onChange={(e) => setValues({ ...values, [key]: e.target.value })} className={`${inputClass} mt-1 w-full`} /></label>)}<label className="text-sm">Inicio impreso<input aria-label="Inicio impreso" type="date" required value={start} onChange={(e) => setStart(e.target.value)} className={`${inputClass} mt-1 w-full`} /></label><label className="text-sm">Fin impreso<input aria-label="Fin impreso" type="date" required value={end} onChange={(e) => setEnd(e.target.value)} className={`${inputClass} mt-1 w-full`} /></label></div>
    {([['countsUnavailable','El banco no imprime conteos de movimientos'],['accountConfirmed','La cuenta y la moneda coinciden con el original'],['coverageConfirmed','El documento cubre todo el mes, sin páginas faltantes'],['originalReviewed','Revisé el archivo original y sus controles']] as const).map(([key,label]) => <label key={key} className="flex items-start gap-2 text-sm"><input type="checkbox" checked={checks[key]} onChange={(e) => setChecks({ ...checks, [key]: e.target.checked })} />{label}</label>)}
    <label className="block text-sm">Nota de verificación<input required minLength={8} maxLength={1000} value={reason} onChange={(e) => setReason(e.target.value)} className={`${inputClass} mt-1 w-full`} /></label><button type="submit" disabled={disabled} className={buttonClass}>Revisar verificación</button>
  </form>;
}
